### ISSUE TITLE
PouchDB 6.2.0 - db.type() is deprecated

### ISSUE THREAD

**Issue by tcoats** [pouchdb-community/pouchdb-replication-stream#63]
I believe this repo needs upgrading to avoid this deprecated warning.

`db.type() is deprecated and will be removed in a future version of PouchDB`

**Comment by bioleyl** [comment]
Same problem for me. Would be perfect to avoid this warning because it fires thousand times in the console when we dump.

**Comment by pubkey** [comment]
Is anyone working on a PR for this?

**Comment by cepm-nate** [comment]
If anyone does, could they please post here so we don't duplicate efforts?

**Comment by AdrianoFerrari** [comment]
Seemed like a straight-forward fix (using other pouchdb libraries as reference for how they handled this).
Can the PR #74 be merged, @nolanlawson ?

**Comment by abhishiv** [comment]
Hey guys, I'm using 1.2.9 but still seeing this log. Am I missing something?

**Comment by lgarron** [comment]
This... still seems to be an issue. 😕
